export const Overwatch_Heroes = [
  {id: 0, name: 'Ana', rank: 0, count: 0, pickRate: 0, overall: 0},
  {id: 1, name: 'Bastion', rank: 0, count: 0, pickRate: 0, overall: 0},
  {id: 2, name: 'Brigitte', rank: 0, count: 0, pickRate: 0, overall: 0},
  {id: 3, name: 'D.Va', rank: 0, count: 0, pickRate: 0, overall: 0},
  {id: 4, name: 'Doomfist', rank: 0, count: 0, pickRate: 0, overall: 0},
  {id: 5, name: 'Genji', rank: 0, count: 0, pickRate: 0, overall: 0},
  {id: 6, name: 'Hanzo', rank: 0, count: 0, pickRate: 0, overall: 0},
  {id: 7, name: 'Junkrat', rank: 0, count: 0, pickRate: 0, overall: 0},
  {id: 8, name: 'Lucio', rank: 0, count: 0, pickRate: 0, overall: 0},
  {id: 9, name: 'McCree', rank: 0, count: 0, pickRate: 0, overall: 0},
  {id: 10, name: 'Mei', rank: 0, count: 0, pickRate: 0, overall: 0},
  {id: 11, name: 'Mercy', rank: 0, count: 0, pickRate: 0, overall: 0},
  {id: 12, name: 'Moira', rank: 0, count: 0, pickRate: 0, overall: 0},
  {id: 13, name: 'Orisa', rank: 0, count: 0, pickRate: 0, overall: 0},
  {id: 14, name: 'Pharah', rank: 0, count: 0, pickRate: 0, overall: 0},
  {id: 15, name: 'Reaper', rank: 0, count: 0, pickRate: 0, overall: 0},
  {id: 16, name: 'Reinhardt', rank: 0, count: 0, pickRate: 0, overall: 0},
  {id: 17, name: 'Roadhog', rank: 0, count: 0, pickRate: 0, overall: 0},
  {id: 18, name: 'Soldier: 76', rank: 0, count: 0, pickRate: 0, overall: 0},
  {id: 19, name: 'Sombra', rank: 0, count: 0, pickRate: 0, overall: 0},
  {id: 20, name: 'Symmetra', rank: 0, count: 0, pickRate: 0, overall: 0},
  {id: 21, name: 'Torbjörn', rank: 0, count: 0, pickRate: 0, overall: 0},
  {id: 22, name: 'Tracer', rank: 0, count: 0, pickRate: 0, overall: 0},
  {id: 23, name: 'Widowmaker', rank: 0, count: 0, pickRate: 0, overall: 0},
  {id: 24, name: 'Winston', rank: 0, count: 0, pickRate: 0, overall: 0},
  {id: 25, name: 'Zarya', rank: 0, count: 0, pickRate: 0, overall: 0},
  {id: 26, name: 'Zenyatta', rank: 0, count: 0, pickRate: 0, overall: 0},
];

export const Schulfächer = [
  {id: 0, name: 'Mathe', rank: 0, count: 0, pickRate: 0, overall: 0},
  {id: 1, name: 'Englisch', rank: 0, count: 0, pickRate: 0, overall: 0},
  {id: 2, name: 'Deutsch', rank: 0, count: 0, pickRate: 0, overall: 0},
  {id: 3, name: 'Physik', rank: 0, count: 0, pickRate: 0, overall: 0},
  {id: 4, name: 'Chemie', rank: 0, count: 0, pickRate: 0, overall: 0},
  {id: 5, name: 'Sport', rank: 0, count: 0, pickRate: 0, overall: 0},
  {id: 6, name: 'Biologie', rank: 0, count: 0, pickRate: 0, overall: 0},
  {id: 7, name: 'Erdkunde', rank: 0, count: 0, pickRate: 0, overall: 0},
  {id: 8, name: 'Geschichte', rank: 0, count: 0, pickRate: 0, overall: 0},
  {id: 9, name: 'PW', rank: 0, count: 0, pickRate: 0, overall: 0},
  {id: 10, name: 'Kunst', rank: 0, count: 0, pickRate: 0, overall: 0},
  {id: 11, name: 'Musik', rank: 0, count: 0, pickRate: 0, overall: 0},
  {id: 12, name: 'Französisch', rank: 0, count: 0, pickRate: 0, overall: 0},
  {id: 13, name: 'Latein', rank: 0, count: 0, pickRate: 0, overall: 0},
  {id: 14, name: 'Spanisch', rank: 0, count: 0, pickRate: 0, overall: 0},
  {id: 15, name: 'Ethik', rank: 0, count: 0, pickRate: 0, overall: 0},
];