export default [{
  id: 0,
  name: 'ABC',
  data: [
    {id: 0, name: 'A', color: '#FF0000'},
    {id: 1, name: 'B', color: '#00FF00'},
    {id: 2, name: 'C', color: '#0000FF'},
  ]
}, {
  id: 1,
  name: 'ABCD',
  data: [
    {id: 0, name: 'A', color: '#FF0000'},
    {id: 1, name: 'B'},
    {id: 2, name: 'C'},
    {id: 3, name: 'D'},
  ]
}, {
  id: 2,
  name: 'ABCDE',
  data: [
    {id: 0, name: 'A'},
    {id: 1, name: 'B'},
    {id: 2, name: 'C'},
    {id: 3, name: 'D'},
    {id: 4, name: 'E'},
  ]
}, {
  id: 3,
  name : 'Overwatch Heroes',
  color: '#3c474b',
  data: [
    {id: 0, name: 'Ana', color: '#718ab3'},
    {id: 1, name: 'Bastion', color: '#7c8f7b'},
    {id: 2, name: 'Brigitte', color: '#be736e'},
    {id: 3, name: 'D.Va', color: '#ed93c7'},
    {id: 4, name: 'Doomfist', color: '#815049'},
    {id: 5, name: 'Genji', color: '#97ef43'},
    {id: 6, name: 'Hanzo', color: '#b9b48a'},
    {id: 7, name: 'Junkrat', color: '#ecbd53'},
    {id: 8, name: 'Lucio', color: '#85c952'},
    {id: 9, name: 'McCree', color: '#ae595c'},
    {id: 10, name: 'Mei', color: '#6faced'},
    {id: 11, name: 'Mercy', color: '#ebe8bb'},
    {id: 12, name: 'Moira', color: '#803c51'},
    {id: 13, name: 'Orisa', color: '#468c43'},
    {id: 14, name: 'Pharah', color: '#3e7dca'},
    {id: 15, name: 'Reaper', color: '#7d3e51'},
    {id: 16, name: 'Reinhardt', color: '#929da3'},
    {id: 17, name: 'Roadhog', color: '#b68c52'},
    {id: 18, name: 'Soldier: 76', color: '#697794'},
    {id: 19, name: 'Sombra', color: '#7359ba'},
    {id: 20, name: 'Symmetra', color: '#8ebccc'},
    {id: 21, name: 'Torbjörn', color: '#c0726e'},
    {id: 22, name: 'Tracer', color: '#d79342'},
    {id: 23, name: 'Widowmaker', color: '#9e6aa8'},
    {id: 24, name: 'Winston', color: '#a2a6bf'},
    {id: 25, name: 'Zarya', color: '#e77eb6'},
    {id: 26, name: 'Zenyatta', color: '#ede582'},
  ]
}, {
  id: 4,
  name : 'Schulfächer',
  data : [
    {id: 0, name: 'Mathe'},
    {id: 1, name: 'Englisch'},
    {id: 2, name: 'Deutsch'},
    {id: 3, name: 'Physik'},
    {id: 4, name: 'Chemie'},
    {id: 5, name: 'Sport'},
    {id: 6, name: 'Biologie'},
    {id: 7, name: 'Erdkunde'},
    {id: 8, name: 'Geschichte'},
    {id: 9, name: 'PW'},
    {id: 10, name: 'Kunst'},
    {id: 11, name: 'Musik'},
    {id: 12, name: 'Französisch'},
    {id: 13, name: 'Latein'},
    {id: 14, name: 'Spanisch'},
    {id: 15, name: 'Ethik'},
  ]
}, {
  id: 5,
  name: 'Pokémon 1. Generation',
  data: [
    {id: 1, name: 'Bisasam'},
    {id: 2, name: 'Bisaknosp'},
    {id: 3, name: 'Bisaflor'},
    {id: 4, name: 'Glumanda'},
    {id: 5, name: 'Glutexo'},
    {id: 6, name: 'Glurak'},
    {id: 7, name: 'Schiggy'},
    {id: 8, name: 'Schillok'},
    {id: 9, name: 'Turtok'},
    {id: 10, name: 'Raupy'},
    {id: 11, name: 'Safcon'},
    {id: 12, name: 'Smettbo'},
    {id: 13, name: 'Hornliu'},
    {id: 14, name: 'Kokuna'},
    {id: 15, name: 'Bibor'},
    {id: 16, name: 'Taubsi'},
    {id: 17, name: 'Tauboga'},
    {id: 18, name: 'Tauboss'},
    {id: 19, name: 'Rattfratz'},
    {id: 20, name: 'Rattikarl'},
    {id: 21, name: 'Habitak'},
    {id: 22, name: 'Ibitak'},
    {id: 23, name: 'Rettan'},
    {id: 24, name: 'Arbok'},
    {id: 25, name: 'Pikachu'},
    {id: 26, name: 'Raichu'},
    {id: 27, name: 'Sandan'},
    {id: 28, name: 'Sandamer'},
    {id: 29, name: 'Nidoran (w)'},
    {id: 30, name: 'Nidorina'},
    {id: 31, name: 'Nidoqueen'},
    {id: 32, name: 'Nidoran (m)'},
    {id: 33, name: 'Nidorino'},
    {id: 34, name: 'Nidoking'},
    {id: 35, name: 'Piepi'},
    {id: 36, name: 'Pixi'},
    {id: 37, name: 'Vulpix'},
    {id: 38, name: 'Vulnona'},
    {id: 39, name: 'Pummeluff'},
    {id: 40, name: 'Knuddeluff'},
    {id: 41, name: 'Zubat'},
    {id: 42, name: 'Golbat'},
    {id: 43, name: 'Myrapla'},
    {id: 44, name: 'Duflor'},
    {id: 45, name: 'Giflor'},
    {id: 46, name: 'Paras'},
    {id: 47, name: 'Parasek'},
    {id: 48, name: 'Bluzuk'},
    {id: 49, name: 'Omot'},
    {id: 50, name: 'Digda'},
    {id: 51, name: 'Digdri'},
    {id: 52, name: 'Mauzi'},
    {id: 53, name: 'Snobilikat'},
    {id: 54, name: 'Enton'},
    {id: 55, name: 'Entoron'},
    {id: 56, name: 'Menki'},
    {id: 57, name: 'Rasaff'},
    {id: 58, name: 'Fukano'},
    {id: 59, name: 'Arkani'},
    {id: 60, name: 'Quapsel'},
    {id: 61, name: 'Quaputzi'},
    {id: 62, name: 'Quappo'},
    {id: 63, name: 'Abra'},
    {id: 64, name: 'Kadabra'},
    {id: 65, name: 'Simsala'},
    {id: 66, name: 'Machollo'},
    {id: 67, name: 'Maschok'},
    {id: 68, name: 'Machomei'},
    {id: 69, name: 'Knofensa'},
    {id: 70, name: 'Ultrigaria'},
    {id: 71, name: 'Sarzenia'},
    {id: 72, name: 'Tentacha'},
    {id: 73, name: 'Tentoxa'},
    {id: 74, name: 'Kleinstein'},
    {id: 75, name: 'Georok'},
    {id: 76, name: 'Geowaz'},
    {id: 77, name: 'Ponita'},
    {id: 78, name: 'Gallopa'},
    {id: 79, name: 'Flegmon'},
    {id: 80, name: 'Lahmus'},
    {id: 81, name: 'Magnetilo'},
    {id: 82, name: 'Magneton'},
    {id: 83, name: 'Porenta'},
    {id: 84, name: 'Dodu'},
    {id: 85, name: 'Dodri'},
    {id: 86, name: 'Jurob'},
    {id: 87, name: 'Jugong'},
    {id: 88, name: 'Sleima'},
    {id: 89, name: 'Sleimok'},
    {id: 90, name: 'Muschas'},
    {id: 91, name: 'Austos'},
    {id: 92, name: 'Nebulak'},
    {id: 93, name: 'Apollo'},
    {id: 94, name: 'Gengar'},
    {id: 95, name: 'Onix'},
    {id: 96, name: 'Traumato'},
    {id: 97, name: 'Hypno'},
    {id: 98, name: 'Krabby'},
    {id: 99, name: 'Kingler'},
    {id: 100, name: 'Voltobal'},
    {id: 101, name: 'Lektrobal'},
    {id: 102, name: 'Owei'},
    {id: 103, name: 'Kokowei'},
    {id: 104, name: 'Tragosso'},
    {id: 105, name: 'Knogga'},
    {id: 106, name: 'Kicklee'},
    {id: 107, name: 'Nockchan'},
    {id: 108, name: 'Schlurp'},
    {id: 109, name: 'Smogon'},
    {id: 110, name: 'Smogmog'},
    {id: 111, name: 'Rihorn'},
    {id: 112, name: 'Rizeros'},
    {id: 113, name: 'Chaneira'},
    {id: 114, name: 'Tangela'},
    {id: 115, name: 'Kangama'},
    {id: 116, name: 'Seeper'},
    {id: 117, name: 'Seemon'},
    {id: 118, name: 'Goldini'},
    {id: 119, name: 'Golking'},
    {id: 120, name: 'Sterndu'},
    {id: 121, name: 'Starmie'},
    {id: 122, name: 'Pantimos'},
    {id: 123, name: 'Sichlor'},
    {id: 124, name: 'Rossana'},
    {id: 125, name: 'Elektek'},
    {id: 126, name: 'Magmar'},
    {id: 127, name: 'Pinsir'},
    {id: 128, name: 'Tauros'},
    {id: 129, name: 'Karpador'},
    {id: 130, name: 'Garados'},
    {id: 131, name: 'Lapras'},
    {id: 132, name: 'Ditto'},
    {id: 133, name: 'Evoli'},
    {id: 134, name: 'Aquana'},
    {id: 135, name: 'Blitza'},
    {id: 136, name: 'Flamara'},
    {id: 137, name: 'Porygon'},
    {id: 138, name: 'Amonitas'},
    {id: 139, name: 'Amoroso'},
    {id: 140, name: 'Kabuto'},
    {id: 141, name: 'Kabutops'},
    {id: 142, name: 'Aerodactyl'},
    {id: 143, name: 'Relaxo'},
    {id: 144, name: 'Arktos'},
    {id: 145, name: 'Zapdos'},
    {id: 146, name: 'Lavados'},
    {id: 147, name: 'Dratini'},
    {id: 148, name: 'Dragonir'},
    {id: 149, name: 'Dragoran'},
    {id: 150, name: 'Mewtu'},
    {id: 151, name: 'Mew'},
  ]
}];